import {PublicKey,SystemProgram,TransactionInstruction,type AccountMeta} from "@solana/web3.js";import {TOKEN_PROGRAM_ID} from "@solana/spl-token";
export const PROGRAM_ID=new PublicKey("BvTUyzWLwyoX47bXndjupDzzbtHBFGNWUsZhwsFNkTXe");export const [CONFIG]=PublicKey.findProgramAddressSync([Buffer.from("config")],PROGRAM_ID);
const u64=(n:bigint)=>{const b=Buffer.alloc(8);b.writeBigUInt64LE(n);return b};const ix=(keys:AccountMeta[],data:Buffer)=>new TransactionInstruction({programId:PROGRAM_ID,keys,data});
export const memberPda=(u:PublicKey)=>PublicKey.findProgramAddressSync([Buffer.from("member"),u.toBuffer()],PROGRAM_ID)[0];
export const proposalPda=(u:PublicKey,n:bigint)=>PublicKey.findProgramAddressSync([Buffer.from("proposal"),u.toBuffer(),u64(n)],PROGRAM_ID)[0];
export const receiptPda=(p:PublicKey,u:PublicKey)=>PublicKey.findProgramAddressSync([Buffer.from("vote"),p.toBuffer(),u.toBuffer()],PROGRAM_ID)[0];
export const joinIx=(u:PublicKey)=>ix([{pubkey:u,isSigner:true,isWritable:true},{pubkey:memberPda(u),isSigner:false,isWritable:true},{pubkey:CONFIG,isSigner:false,isWritable:true},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}],Buffer.from([1]));
export const claimIx=(u:PublicKey,treasury:PublicKey,dest:PublicKey)=>ix([{pubkey:u,isSigner:true,isWritable:false},{pubkey:memberPda(u),isSigner:false,isWritable:true},{pubkey:CONFIG,isSigner:false,isWritable:false},{pubkey:treasury,isSigner:false,isWritable:true},{pubkey:dest,isSigner:false,isWritable:true},{pubkey:TOKEN_PROGRAM_ID,isSigner:false,isWritable:false}],Buffer.from([2]));
export const createProposalIx=(u:PublicKey,n:bigint,vault:PublicKey)=>ix([{pubkey:u,isSigner:true,isWritable:true},{pubkey:proposalPda(u,n),isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:false},{pubkey:CONFIG,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}],Buffer.concat([Buffer.from([3]),u64(n)]));
export const voteIx=(u:PublicKey,p:PublicKey,source:PublicKey,vault:PublicKey,option:number,amount:bigint)=>ix([{pubkey:u,isSigner:true,isWritable:true},{pubkey:p,isSigner:false,isWritable:true},{pubkey:receiptPda(p,u),isSigner:false,isWritable:true},{pubkey:source,isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:CONFIG,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false},{pubkey:TOKEN_PROGRAM_ID,isSigner:false,isWritable:false}],Buffer.concat([Buffer.from([4,option]),u64(amount)]));
export const settleIx=(p:PublicKey,vault:PublicKey,treasury:PublicKey)=>ix([{pubkey:p,isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:CONFIG,isSigner:false,isWritable:false},{pubkey:treasury,isSigner:false,isWritable:true},{pubkey:TOKEN_PROGRAM_ID,isSigner:false,isWritable:false}],Buffer.from([5]));
export type Config={mint:PublicKey;treasury:PublicKey;total:bigint;allocated:bigint};export function parseConfig(d:Buffer):Config{if(d.length!==96||d[0]!==1)throw Error("Invalid config");return{mint:new PublicKey(d.subarray(8,40)),treasury:new PublicKey(d.subarray(40,72)),total:d.readBigUInt64LE(72),allocated:d.readBigUInt64LE(80)}}
